version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-forwarding-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=5000
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./secure_session.enc:/app/secure_session.enc
      - ./new_session.txt:/app/new_session.txt
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:16-alpine
    container_name: telegram-bot-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=telegram_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telegram_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: